# Generated by Django 3.0.5 on 2020-04-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('you', models.CharField(max_length=255, null=True)),
                ('bot', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Adverticements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(choices=[('(0-2)', '(0-2)'), ('(4-6)', '(4-6)'), ('(8-12)', '(8-12)'), ('(15-20)', '(15-20)'), ('(25-32)', '(25-32)'), ('(38-43)', '(38-43)'), ('(48-53)', '(48-53)'), ('(60-100)', '(60-100)')], max_length=20)),
                ('images', models.ManyToManyField(to='Project.Images')),
            ],
        ),
    ]
